export const GET_COUNTRIES ='GET_COUNTRIES';
export const COUNTRIES_ERROR ='COUNTRIES_ERROR';
export const GET_ITEMS ='GET_ITEMS';
export const GET_COUNTRIES_WITH ='GET_COUNTRIES_WITH';
export const GET_LOADING= 'GET_LOADING';